export const products = [
    {
        cod:1001,
        categoria:"MontainBike",
        nombre:"Giant Talon 1",
        imagen:'../../assets/img/productos/giant-talon1.jpg',
        marca:"Giant",
        modelo:2022,
        color:"Gris",
        stock:5,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:85000 
    },
    {
        cod:1002,
        categoria:"MontainBike",
        nombre:"Giant Talon 2",
        imagen:"giant-talon2.jpg",
        marca:"Giant",
        modelo:2021,
        color:"Azul metal",
        stock:3,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:98000
    },
    {
        cod:1003,
        categoria:"MontainBike",
        nombre:"Giant Talon 3",
        imagen:"giant-talon3.jpg",
        marca:"Giant",
        modelo:2021,
        color:"Azul y Negro",
        stock:3,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:105000
    },
    {
        cod:1004,
        categoria:"MontainBike",
        nombre:"Giant Talon 4",
        imagen:"giant-talon4.jpg",
        marca:"Giant",
        "modelo":2021,
        color:"Negra",
        stock:3,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:250000
    },
    {
        cod:1005,
        categoria:"MontainBike",
        nombre:"Giant Fathon",
        imagen:"fathon.jpg",
        marca:"Giant",
        "modelo":2021,
        color:"Negra y azul",
        stock:3,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:350000
    },
    {
        cod:1006,
        categoria:"MontainBike",
        nombre:"Giant Advanced Pro",
        imagen:"advanced.jpg",
        marca:"Giant",
        "modelo":2022,
        color:"Naranja y Negro",
        stock:4,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1200000
    },
    {
        cod:1029,
        categoria:"Downhill",
        nombre:"Trek Session 8",
        imagen:"session 8-down.jpg",
        marca:"Trek",
        "modelo":2022,
        color:"Verde Militar",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1900000
    },
    {
        cod:1028,
        categoria:"Downhill",
        nombre:"Giant Scorpion",
        imagen:"giant-down.jpg",
        marca:"Giant",
        modelo:2022,
        color:"Negro y Azul",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1320000
    },
    {
        cod:1027,
        categoria:"Ruta",
        nombre:"Giant Advanced",
        imagen:"advanced-ruta.jpg",
        marca:"Giant",
        modelo:2022,
        color:"Blanca",
        stock:6,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:300000
    },
    {
        cod:1026,
        categoria:"Ruta",
        nombre:"Giant TCR",
        imagen:"tcr-ruta.jpg",
        marca:"Giant",
        modelo:2022,
        color:"Negro y Azul",
        stock:4,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:380000
    },
    {
        cod:1025,
        categoria:"Ruta",
        nombre:"Giant SRC",
        imagen:"src-ruta.jpg",
        marca:"Giant",
        modelo:2022,
        color:"Negro y Azul",
        stock:5,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:320000
    },
    {
        cod:1024,
        categoria:"Ruta",
        nombre:"Giant Contend",
        imagen:"contend-ruta.jpg",
        marca:"Giant",
        modelo:2022,
        color:"Negro y Naranja",
        stock:2,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:580000
    },
    {
        cod:1023,
        categoria:"Ruta",
        nombre:"Trek Emonda",
        imagen:"emonda-ruta.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Roja y Azul",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:900000
    },
    {
        cod:1022,
        categoria:"Ruta",
        nombre:"Trek Emonda Pro",
        imagen:"emonda pro-ruta.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Azul y Celeste",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1350000
    },
    {
        cod:1021,
        categoria:"Ruta",
        nombre:"Trek Madone",
        imagen:"madone-ruta.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Negro y gris",
        stock:5,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:590000
    },
    {
        cod:1020,
        categoria:"Ruta",
        nombre:"Trek Domane",
        imagen:"domane-ruta.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Rojo",
        stock:3,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:800000

    },
    {
        cod:1019,
        categoria:"Ruta",
        nombre:"Trek Concept SL",
        imagen:"concept-ruta.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Rojo y Negro",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:790000
    },
    {
        cod:1018,
        categoria:"Ruta",
        nombre:"Trek Madone SL",
        imagen:"madone-sl-ruta.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Blanca",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:700000
    },
    {
        cod:1017,
        categoria:"MontainBike",
        nombre:"Venzo Vulcan",
        imagen:"vulcan.jpg",
        marca:"Venzo",
        modelo:2022,
        color:"Rojo y Negro",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:790000
    },
    {
        cod:1016,
        categoria:"MontainBike",
        nombre:"Venzo Stinger",
        imagen:"venzo-stinger.jpg",
        marca:"Venzo",
        modelo:2022,
        color:"Verde",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:685000
    },
    {
        cod:1015,
        categoria:"MontainBike",
        nombre:"Venzo Elemento",
        imagen:"elemento.jpg",
        marca:"Venzo",
        modelo:2022,
        color:"Rojo y Negro",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:485000
    },
    {
        cod:1014,
        categoria:"MontainBike",
        nombre:"Trek Pro-Caliver 9",
        imagen:"procaliver9.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Negra",
        stock:5,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:899000
    },
    {
        cod:1013,
        categoria:"MontainBike",
        nombre:"Trek Pro-Caliver 8",
        imagen:"procaliver8.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Gris",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:790000
    },
    {
        cod:1012,
        categoria:"MontainBike",
        nombre:"Trek Pro-Caliver 7",
        imagen:"procaliver7.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Negra",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:685000
    },
    {
        cod:1011,
        categoria:"MontainBike",
        nombre:"Trek X-Caliver 9",
        imagen:"xcaliver9.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Gris",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:485000
    },
    {
        cod:1010,
        categoria:"MontainBike",
        nombre:"Trek X-Caliver 8",
        imagen:"xcaliver8.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Rojo",
        stock:2,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:325000
    },
    {
        cod:1009,
        categoria:"MontainBike",
        nombre:"Trek X-Caliver 7",
        imagen:"xcaliver7.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Azul",
        stock:5,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:285000
    },
    {
        cod:1008,
        categoria:"MontainBike",
        nombre:"Trek Marlin 5",
        imagen:"marlin5.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Negro",
        stock:5,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:95000
    },
    {
        cod:1007,
        categoria:"MontainBike",
        nombre:"Giant Advanced",
        imagen:"advanced29.jpg",
        marca:"Giant",
        modelo:2022,
        color:"Negro y Bordo",
        stock:4,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:900000
    },
    {
        cod:1030,
        categoria:"Downhill",
        nombre:"Trek Session 9.6",
        imagen:"session-down.jpg",
        marca:"Trek",
        modelo:2022,
        color:"Roja",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:2200000
    },
    {
        cod:1031,
        categoria:"Downhill",
        nombre:"Scott XLC",
        imagen:"scott-down.jpg",
        marca:"Scott",
        modelo:2022,
        color:"Gris",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1790000
    },
    {
        cod:1032,
        categoria:"Downhill",
        nombre:"Capierre Atiwit",
        imagen:"atiwit-down.jpg",
        marca:"Capierre",
        modelo:2022,
        color:"Rojo",
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1290000
    },
    {
        cod:1033,
        categoria:"Downhill",
        nombre:"Scott GLory 2022",
        imagen:"glory-down.jpg",
        marca:"Scott",
        modelo:2022,
        color:"Dorada",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1590000
    },]