import img1 from '../assets/img/productos/giant-talon1.jpg';
import img2 from '../assets/img/productos/giant-talon-2.jpg';
import img3 from '../assets/img/productos/giant-talon3.jpg'
import img4 from '../assets/img/productos/giant-talon4.jpg'
import img5 from '../assets/img/productos/fathon.jpg'
import img6 from '../assets/img/productos/advanced.jpg'
import img7 from '../assets/img/productos/session 8-down.jpg'
import img8 from '../assets/img/productos/giant-down.jpg'
import img9 from '../assets/img/productos/advanced-ruta.jpg'
import img10 from '../assets/img/productos/tcr-ruta.jpg'
import img11 from '../assets/img/productos/src-ruta.jpg'
import img12 from '../assets/img/productos/contend-ruta.jpg'
import img13 from '../assets/img/productos/emonda-ruta.jpg'
import img14 from '../assets/img/productos/emonda pro-ruta.jpg'
import img15 from '../assets/img/productos/madone-ruta.jpg'
import img16 from '../assets/img/productos/domane-ruta.jpg'
import img17 from '../assets/img/productos/domane-ruta.jpg'
import img18 from '../assets/img/productos/madone-sl-ruta.jpg'
import img19 from '../assets/img/productos/vulcan.jpg'
import img20 from '../assets/img/productos/venzo-stinger.jpg'
import img21 from '../assets/img/productos/elemento.jpg'
import img22 from '../assets/img/productos/procaliver9.jpg'
import img23 from '../assets/img/productos/procaliver8.jpg'
import img24 from '../assets/img/productos/procaliver7.jpg'
import img25 from '../assets/img/productos/xcaliver9.jpg'
import img26 from '../assets/img/productos/xcaliver8.jpg'
import img27 from '../assets/img/productos/xcaliver7.jpg'
import img28 from '../assets/img/productos/marlin5.jpg'
import img29 from '../assets/img/productos/advanced29.jpg'
import img30 from '../assets/img/productos/session-down.jpg'
import img31 from '../assets/img/productos/scott-down.jpg'
import img32 from '../assets/img/productos/atiwit-down.jpg'
import img33 from '../assets/img/productos/glory-down.jpg'


export const products = [
    {
        cod:1001,
        categoria:"MontainBike",
        nombre:"Giant Talon 1",
        imagen:img1,
        marca:"Giant",
        modelo:2022,
        color:"Gris",
        stock:5,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:85000 ,
        material: 'Aluminio',
    },
    {
        cod:1002,
        categoria:"MontainBike",
        nombre:"Giant Talon 2",
        imagen:img2,
        marca:"Giant",
        modelo:2021,
        color:"Azul metal",
        stock:3,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:98000,
        material: 'Aluminio',
    },
    {
        cod:1003,
        categoria:"MontainBike",
        nombre:"Giant Talon 3",
        imagen:img3,
        marca:"Giant",
        modelo:2021,
        color:"Azul y Negro",
        stock:3,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:105000,
        material: 'Aluminio',
    },
    {
        cod:1004,
        categoria:"MontainBike",
        nombre:"Giant Talon 4",
        imagen:img4,
        marca:"Giant",
        "modelo":2021,
        color:"Negra",
        stock:3,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:250000,
        material: 'Aluminio',
    },
    {
        cod:1005,
        categoria:"MontainBike",
        nombre:"Giant Fathon",
        imagen:img5,
        marca:"Giant",
        "modelo":2021,
        color:"Negra y azul",
        stock:3,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:350000,
        material: 'Aluminio',
    },
    {
        cod:1006,
        categoria:"MontainBike",
        nombre:"Giant Advanced Pro",
        imagen:img6,
        marca:"Giant",
        "modelo":2022,
        color:"Naranja y Negro",
        stock:4,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1200000,
        material: 'Aluminio',
    },
    {
        cod:1029,
        categoria:"Downhill",
        nombre:"Trek Session 8",
        imagen:img7,
        marca:"Trek",
        "modelo":2022,
        color:"Verde Militar",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1900000,
        material: 'Aluminio',
    },
    {
        cod:1028,
        categoria:"Downhill",
        nombre:"Giant Scorpion",
        imagen:img8,
        marca:"Giant",
        modelo:2022,
        color:"Negro y Azul",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1320000,
        material: 'Aluminio',
    },
    {
        cod:1027,
        categoria:"Ruta",
        nombre:"Giant Advanced",
        imagen:img9,
        marca:"Giant",
        modelo:2022,
        color:"Blanca",
        stock:6,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:300000,
        material: 'Aluminio',
    },
    {
        cod:1026,
        categoria:"Ruta",
        nombre:"Giant TCR",
        imagen:img10,
        marca:"Giant",
        modelo:2022,
        color:"Negro y Azul",
        stock:4,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:380000,
        material: 'Aluminio',
    },
    {
        cod:1025,
        categoria:"Ruta",
        nombre:"Giant SRC",
        imagen:img11,
        marca:"Giant",
        modelo:2022,
        color:"Negro y Azul",
        stock:5,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:320000,
        material: 'Aluminio',
    },
    {
        cod:1024,
        categoria:"Ruta",
        nombre:"Giant Contend",
        imagen:img12,
        marca:"Giant",
        modelo:2022,
        color:"Negro y Naranja",
        stock:2,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:580000,
        material: 'Aluminio',
    },
    {
        cod:1023,
        categoria:"Ruta",
        nombre:"Trek Emonda",
        imagen:img13,
        marca:"Trek",
        modelo:2022,
        color:"Roja y Azul",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:900000,
        material: 'Aluminio',
    },
    {
        cod:1022,
        categoria:"Ruta",
        nombre:"Trek Emonda Pro",
        imagen:img14,
        marca:"Trek",
        modelo:2022,
        color:"Azul y Celeste",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1350000,
        material: 'Aluminio',
    },
    {
        cod:1021,
        categoria:"Ruta",
        nombre:"Trek Madone",
        imagen:img15,
        marca:"Trek",
        modelo:2022,
        color:"Negro y gris",
        stock:5,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:590000,
        material: 'Aluminio',
    },
    {
        cod:1020,
        categoria:"Ruta",
        nombre:"Trek Domane",
        imagen:img16,
        marca:"Trek",
        modelo:2022,
        color:"Rojo",
        stock:3,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:800000,
        material: 'Aluminio',

    },
    {
        cod:1019,
        categoria:"Ruta",
        nombre:"Trek Concept SL",
        imagen:img17,
        marca:"Trek",
        modelo:2022,
        color:"Rojo y Negro",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:790000,
        material: 'Aluminio',
    },
    {
        cod:1018,
        categoria:"Ruta",
        nombre:"Trek Madone SL",
        imagen:img18,
        marca:"Trek",
        modelo:2022,
        color:"Blanca",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:700000,
        material: 'Aluminio',
    },
    {
        cod:1017,
        categoria:"MontainBike",
        nombre:"Venzo Vulcan",
        imagen:img19,
        marca:"Venzo",
        modelo:2022,
        color:"Rojo y Negro",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:790000,
        material: 'Aluminio',
    },
    {
        cod:1016,
        categoria:"MontainBike",
        nombre:"Venzo Stinger",
        imagen:img20,
        marca:"Venzo",
        modelo:2022,
        color:"Verde",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:685000,
        material: 'Aluminio',
    },
    {
        cod:1015,
        categoria:"MontainBike",
        nombre:"Venzo Elemento",
        imagen:img21,
        marca:"Venzo",
        modelo:2022,
        color:"Rojo y Negro",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:485000,
        material: 'Aluminio',
    },
    {
        cod:1014,
        categoria:"MontainBike",
        nombre:"Trek Pro-Caliver 9",
        imagen:img22,
        marca:"Trek",
        modelo:2022,
        color:"Negra",
        stock:5,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:899000,
        material: 'Aluminio',
    },
    {
        cod:1013,
        categoria:"MontainBike",
        nombre:"Trek Pro-Caliver 8",
        imagen:img23,
        marca:"Trek",
        modelo:2022,
        color:"Gris",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:790000,
        material: 'Aluminio',
    },
    {
        cod:1012,
        categoria:"MontainBike",
        nombre:"Trek Pro-Caliver 7",
        imagen:img24,
        marca:"Trek",
        modelo:2022,
        color:"Negra",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:685000,
        material: 'Aluminio',
    },
    {
        cod:1011,
        categoria:"MontainBike",
        nombre:"Trek X-Caliver 9",
        imagen:img25,
        marca:"Trek",
        modelo:2022,
        color:"Gris",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:485000,
        material: 'Aluminio',
    },
    {
        cod:1010,
        categoria:"MontainBike",
        nombre:"Trek X-Caliver 8",
        imagen:img26,
        marca:"Trek",
        modelo:2022,
        color:"Rojo",
        stock:2,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:325000,
        material: 'Aluminio',
    },
    {
        cod:1009,
        categoria:"MontainBike",
        nombre:"Trek X-Caliver 7",
        imagen:img27,
        marca:"Trek",
        modelo:2022,
        color:"Azul",
        stock:5,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:285000,
        material: 'Aluminio',
    },
    {
        cod:1008,
        categoria:"MontainBike",
        nombre:"Trek Marlin 5",
        imagen:img28,
        marca:"Trek",
        modelo:2022,
        color:"Negro",
        stock:5,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:95000,
        material: 'Aluminio',
    },
    {
        cod:1007,
        categoria:"MontainBike",
        nombre:"Giant Advanced",
        imagen:img29,
        marca:"Giant",
        modelo:2022,
        color:"Negro y Bordo",
        stock:4,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:900000,
        material: 'Aluminio',
    },
    {
        cod:1030,
        categoria:"Downhill",
        nombre:"Trek Session 9.6",
        imagen:img30,
        marca:"Trek",
        modelo:2022,
        color:"Roja",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:2200000,
        material: 'Aluminio',
    },
    {
        cod:1031,
        categoria:"Downhill",
        nombre:"Scott XLC",
        imagen:img31,
        marca:"Scott",
        modelo:2022,
        color:"Gris",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1790000,
        material: 'Aluminio',
    },
    {
        cod:1032,
        categoria:"Downhill",
        nombre:"Capierre Atiwit",
        imagen:img32,
        marca:"Capierre",
        modelo:2022,
        color:"Rojo",
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1290000,
        material: 'Aluminio',
    },
    {
        cod:1033,
        categoria:"Downhill",
        nombre:"Scott GLory 2022",
        imagen:img33,
        marca:"Scott",
        modelo:2022,
        color:"Dorada",
        stock:1,
        initial:1,
        descrption:"si nos organizamos, fiiiiiiiiii todooooooos",
        precio:1590000,
        material: 'Aluminio',
    },]